services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Prevents local node_modules from overriding container's
    environment:
      - NODE_ENV=development
    command: npm start
